const listaDeHorarios = [
    {
        id: 1,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 2,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 3,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 4,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },  
    {
        id: 5,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 6,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },  
    {
        id: 7,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 8,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 9,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 10,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 11,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 12,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        modalidade: "Futebol society",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
];

export default listaDeHorarios;