const listaDeHorarios = [
    {
        id: 101,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 102,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 103,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 104,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },  
    {
        id: 105,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 106,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },  
    {
        id: 107,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 108,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 109,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 110,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 111,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
    {
        id: 112,
        publicadorId: 1,
        estabelecimento: "Arena Exemplo",
        esporte: "Futebol",
        bairro: "Jundiapeba",
        data: "2026-10-10",
        horaInicio: "09:00",
        duracao: 60,
        preco: 100,
        img: ""
    },
];

export default listaDeHorarios;